#include "gtest/gtest.h"

#include <iostream>
#include <string>

#include <iota/iota.h>

TEST(GenerateTest, GenerateKey) {
  auto keyTrytes = std::string(
      "VYWSMHNCTYSHBZHTTWNFIGW9AWZVXCEFTQKRTDQCWTUAGJAGJHQHQUQGMQRUIMR9YARMHLRM"
      "WYBDZHYWVCMWWUJIOM9IPHVUTYBHPHZHAOH9HPLOCPZPMRCSXMNULFCWXGHB9MZEWETCFRRF"
      "9IMYWUMMVCXIOKGPZXOUPV9WVWDMCSJVRUUURSR9TKZAJSXEAXYJTJWOLCUHUZRFGAAYFHKS"
      "GPTEDGUGNHPIFBXS9LZWOTPJHBRNEYDLPFKDEITAWNGXEC9WDQ9TH9B9UCHKZGNTUPUOMYWT"
      "SXSGWZPDW9PCZSIJQQWRDLQUZEXUORKKVYXJXSEASHIWHROFKJJIAWWWGBFGSOBAGDJOIKNT"
      "MQ9RKRZ9CRC99XWEPVPDVHUQAPBSN9UTSDVTEGYKBXAUXZSFLGKKKOHQQASMLSMDIIXWAWGK"
      "CJ9KNAXSRL9ZMFQYKYBJLUSZYODXAKJQQFCZRGQQSOAYRKHQBLFKLSOFPPXGUHDCNGVXMFDT"
      "IELSTCADVZXV9UP9KWZOYZNOEEIALQTNJZKYLR9JOAYJSJGWSJCELQJIBVFURXYQKSZEVJDZ"
      "SHTTQQWAD9FZTUGECDPISVZORWEBSTAE9RQHKSBUNFL9WNUBYEOMEAIIDOFNKXVLQBGNTRME"
      "GECDVGFMWADNWCLBREOMUSACW9EHONFTVYZPAWCOKKNOACEYQTMEHPDXBUPJJNLGJGSZLWMR"
      "O9PSSEH9K99I9TXTVGHWGQIVSMFPDIPLJWFVKQFOOWPQPGDPYWKGARUNNPAXPYW9DTIMQWOQ"
      "MGQDODEJRFENAFVDPXKZLKGWGMARELHBROLOFDVWTCXTGYHVNQGSOVOAAOXXDGKKCWTXIDJG"
      "ATVQRACHXBNUGXFAZTCCQHHUCTKRKYSHAGOEOJZDXLWXPUDGDHKGFIR9BLPPJK9AUYQKXX9V"
      "SHKTVJVSZGS9CPYYKFJWPQFQXBNMGMWWH9KCWKIQCEOCEBQBPNLZFXZGVOI9TSNUEGNFBVVL"
      "WZPFUOARVEDTAALLBOBKSXSDNMI9OYBUMSQVCELIBGNLWDSUQ9ROEDURDPKKEDFSMITBQEZX"
      "FMXEPIUVXUMYEBEOOZWQWDDPOXUMNVIVUH9WH9NQEWMLQPQQVVEQSZBIJDORRHOWYLXABHLE"
      "ZNDZYPURKINLKI9GQUIKGVNROXCPOUYVQISNHO9TDHX9QPSNEXKQAZODFXDXEADUEUBSPJW9"
      "BQMRIKOCMGMGYYMCFXBLM9NXDFKJSBMMZBCZFGYJDXUCHGEDFYMYLLFLGEMUJOWWPMACIGIR"
      "JCMZSJS9CDXKTJWLX9ZJ9TENMCXAFE9TSKFWATFOYOQWJQZGPDLYJHZHVKXSGQYF9HMYW9AM"
      "Z99APXEBGHTVYRQNZLSGBQMRVEIJPQCEXNNTDBSDIN9DPYSFEGXZMXTUXSIDXEXBLPDCYNDX"
      "ESNLMDNYGIV9HG9LZWEXJT9DW9WPIPVYSHUPUPGAOQAOJTCCUOFYKGETDAXZVIATORSLICMR"
      "SK9CJRDEWPPADCUSIVOGSTBHARWRXSVODUERMKRJJOQFWMFIGYDNIIOVXTJI9IMPSU9SBOZM"
      "AMPTWSXWGQLHDABFPQRUDIPTBFKVLAUPVADOYJVQRBTF9VWZ9RYQXLNENFDRMIUGKOWWVGQD"
      "IXUF9MVWHOYLUKOJWYTWVMCGFA9DQQXETGAOYQBZTRZAFXGKCPHLDKHEZJMUSUHYCPYGHTV9"
      "FCTIIKZEZYQSENQUGBCEKQWGCPRPISTMHB9DQTNHKWIFUNXWZLUITUMGKOWNDTGFOTKNPQQW"
      "HDZJNNNA9IQPY9RGRKRFKOSAZWPJLVVKAEQTMUUYXE9NEYQCVDXYYZTGYGYGJTGUHBHZNSTP"
      "9HXKAZXMCLX9EEJMXLVCQV9FQAXI9HWRCHGDLQGLWBOUUBMHWEOAJ9LMAED9UFKZDNYYBQIT"
      "BMMNZWOTFJKZASPNPGHRJTMBVFLKCICUMJZOIVKPNLHICLOOZQCG99JTNEKWFBUONJKAUWAL"
      "GBRSMHQUPVNKUTOXBIPIZQZYMDUTJ9BEWPUFMVSG9JIRKGLHGAFDYWDQQQMIPWIAMJNWAHLU"
      "VN99YORPE99ZLYUPGX9MUDDNSHZPBWWMILIRJKRPWOLGOEXMFKSJKUUTU9GKSGYUTFXBKUWI"
      "TLKWTDXCINGZNIFAZZXXSZULRPICWLXLLIQPYPLMHZNMDSWTTZPYCSAHOZBCYUZDLHDBZEUS"
      "ZMSTJJUKZMCTOUI9EVXOWKDZLAHCVEQSUKDLBYAMSBEPMINZTRMSJTRSJXQFL9ASNMWQMEY9"
      "FYVDJZPUGZXRUQSHEOAIKPCOCYHM9E9DLNHQUFBJWDORIKLAIOJ9EYGJZHIFXJAMOJNAUSUT"
      "JOJKXWJCFAUIEHRMCTOHBSEWTXHECEFYUNO9RMANVUDWKXVUDKYZBLMORJUZCWVEFIJXCVHH"
      "IZVGBB9WPEDNZTPIMXCPRDKWUDMLXKYYXJJPQFVQG9CESCJHPQ9BWQURTIOLSPVKHTTMOVPU"
      "MMJFVXQFOHGJBBOZHUYAUIWBCUMYPMRZCPAHVSCHJBBEP9VXCLULVA9DNDNYOMCFIXMV9GVD"
      "HNNKUOVLSQTDFNXCFQPMYUZSJVJMZWOPXEORLX9ATHONJILLCTIOWQIJLBUCOC9DUCQEXQZ9"
      "EOVYPRKMHUK9VEBMOJXHSHLKEWYADAEPGKSVGBGNRFDBAKXCP9CXSQTPBPZYATZNAWORODLD"
      "LOZRCTSKJOWOQEFWIKCGUYHVYMIWLMXPWPL9NBEQCANYQWXLQGMNTUALTSGHYJZYQVAZHERW"
      "LMLQAWCVKHJQBNBFXMDMHPNLKFI9RIPTS9NRGZPIGCAPMFJYYNVIT9QXGSSGHEEYSPCEQXLJ"
      "WQZLKCFAQVFFMQYABBAVSZ9HDWDCVAIOTMZMOBAZVXZRCN9X9GRHQOUGTQLLF9ARQJYTXKMB"
      "I9LH9UZUXTDDJMLWWXMDXDNEZYDZFG9ZXKPNCRUFGZEVMPBUKMZH99NTS9IGOLNJYAERBMVZ"
      "HCJVIAOYOGWHXSLXJGMSJCINICQTXNAVHMS99XE9SEUZQIMG9QYEASIPKIQGOBRQBQODEDOH"
      "9ZHZEWW9CIEUYBDICXDNIRM9YNQQSP9UMTTHSZDLDIDALHPWUORG9RMHXBJBXK9BTQNBNNZZ"
      "HSEA9AYVLGDDCHBMYHWIHTCSLA9NZNVYKXETY9PQNPWYFZEMILSBKNUQIFJARCNKFUA9ISUO"
      "LDUKEWCIZEEXXXMMNAIFSHGRXTTIYDLTLCWTKKSEAPZNDRXRT9TCXFOIEDWHOBGJLPGRZXLX"
      "ISKBUHLTQGIKNVQZTXBCSJBUJZCTVMBQVENP9AHEMNDUIJHPQPQYKYSFRSUIUTLZRGACVDRP"
      "MCQHBDVMEOGXLLFAAORVFJNKJNWVVZXECAUGZXLYOWEISGORVTLXWYDZNFFPLW9VHHLXAAEI"
      "ZDKJCNGEGIUUAGSUUOGTVWA9GBEGMCPWQVYHCIGPQCNZEFBZVX9GTVENIXCATEFMVTIMYDOW"
      "IXA9EFTGBUUIEJNEJQOHGHINKVJRVPMVHMLJHHBKMVBGEBZMJORQJ9KXWJFIWKRYPUKUK9JE"
      "KQTHUPYGWZ9UEVPQZHAECK9CIZXCYFIRITJNBLSVXIUGKASLTLMQJJHFUKYYXMWBC9SDVYMQ"
      "WBCBXQVODJWHBKZZGKUPKDOXLXTDY9QBU9GPGSGULGJLWFMI9LHAOFFUPNWCQMZS9EZQDSRB"
      "IW9MJJYFGHIGLDCVOAFYQPMXQXTHOZV9XLB9VROWKPVGFJDNRXQQASJZCZLGKVUBCDAFXWLZ"
      "QQGZOFVIKDDCGCYIIRUQLLIGNJYHGJJCHPFPAITPOOANGLQDUFEXRGNGOVMGZUBGJWFXYSHE"
      "QQXIEJZSJTGZTHIYCGWAUSPITGRWBCHDDD9FNBF9PHIFKWSKNIUCWNHN9XFPZBBBRZKFWGZA"
      "UODGMXRKWLSQLOJHDBCZBR9RMJWFYJKHEBMMZIN9ZGYAVJTIAU9XCNPLFF9LWJWYN9IZZXUE"
      "PB9TEJNLVDDDBGWKZHMDMWAEIHLOYGJGLYDIAMNWW9HGBKDCAFYUVMVDUEOQJFK9C9ULBLNO"
      "WAXQZZTDMGUHNOKJLETQIK9VKAWAHHSSRCJOAEONBEXDLNFINUEHLMFABFHKSMSFLOLWOCFL"
      "GFQRGKEWWEZHD9YRRRRWSMMJUSQLIIYNTSRFOULNDQ9DBMGJCJWISOPAIK9LIPTWWTKAIZYW"
      "H9ZHFT9BBQQSASATGFDOTVOSMCIXXBQOTWZYUEGLGQCWAKFGEXEULFJAPTZQDJIBJZUSSM9I"
      "RY9YAIBBM9SXCVVIBKTBNEWRTYAEBBFQYPXORHYBGK9AIQBROCUAZG");
  auto seed = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
              "AAAAAAAAAAAAAAAAA";
  EXPECT_TRUE(iota_isValidTrytes(seed));
  auto computed = std::string(iota_generateKey(seed, 1, 2));

  EXPECT_EQ(computed, keyTrytes);
}
