#pragma once

#define IOTA_TRYTE_ALPHABET "9ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define IOTA_TRYTE_ALPHABET_LENGTH 27
#define IOTA_HASHLEN_TRYTE 81
#define IOTA_HASHLEN_TRIT IOTA_HASHLEN_TRYTE * 3
#define IOTA_STATE_LENGTH IOTA_HASHLEN_TRIT * 3
#define IOTA_FRAGMENT_LENGTH IOTA_STATE_LENGTH * 3
#define IOTA_CHECKSUM_SIZE 9

#define IOTA_SIGNATURE_SIZE 6561
#define IOTA_NUMBER_OF_ROUNDS 27
