#pragma once

#define IOTA_TRYTE_ALPHABET "9ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define IOTA_TRYTE_ALPHABET_LENGTH 27
#define IOTA_TRYTE_LENGTH 81

#define IOTA_SIGNATURE_SIZE 6561
#define IOTA_HASH_SIZE 243

